# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 57b42f3e757a4d842f5612de8e4738c12dcd6c2995f1c51a898b3234aaf9d846bc9fe22c5c7ab75b2c98ceab69c6ca99221d29e2591be9a34e46542b550eb310

test:
  secret_key_base: 847ce328fb8800e459a7179385a16a9efb7a9a581578d2773329669ce9acf374bdd6abef510b0a8d094fa1b278a0c9e7ade9d543278de3537fee8333afa721de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
